services:
  fastapi:
    build: .
    container_name: fastapi_container
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

networks:
  app-net:
    driver: bridge
    external: true
